# ── ConfigMap application Spring Boot
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api-config
  namespace: devops-l3gl
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/product_db"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SERVER_PORT: "8086"
---
# ── Deployment product-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: devops-l3gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: amba1030/product-api:latest
        ports:
        - containerPort: 8086
        envFrom:
        - configMapRef:
            name: product-api-config
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        resources:
          requests:
            cpu: "200m"
            memory: "250Mi"
          limits:
            cpu: "400m"
            memory: "500Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8086
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 3
---
# ── Service ClusterIP product-api
apiVersion: v1
kind: Service
metadata:
  name: product-api-service
  namespace: devops-l3gl
spec:
  selector:
    app: product-api
  ports:
  - port: 8086
    targetPort: 8086
  type: ClusterIP
---
# ── Ingress HTTP
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-api-ingress
  namespace: devops-l3gl
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: product-api-service
            port:
              number: 8086
